name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Rust
        run: |
          rustup toolchain install stable \
            --profile minimal \
            --component rustfmt \
            --component clippy \
            --no-self-update
          rustup default stable

      - name: Cache Cargo dependencies
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run tests
        run: cargo test --quiet

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
